mutation CreateProject($project: CreateProjectInput!) {
  createProject(project: $project) {
    id
    created_at
    name
    internal_name
    domain
    start_date
    end_date
    description
    environment
  }
}
