query Cv($cvId: ID!) {
  cv(cvId: $cvId) {
    id
    created_at
    name
    education
    description
    user {
      id
      email
      position_name
      profile {
        id
        full_name
        avatar
        languages {
          name
          proficiency
        }
      }
    }
    projects {
      id
      name
      internal_name
      description
      domain
      start_date
      end_date
      environment
      roles
      responsibilities
      project {
        id
        name
        internal_name
      }
    }
    skills {
      name
      mastery
      categoryId
    }
    languages {
      name
      proficiency
    }
  }
}
