query User($userId: ID!) {
  user(userId: $userId) {
    id
    created_at
    email
    is_verified
    role
    department_name
    position_name
    profile {
      id
      created_at
      first_name
      last_name
      full_name
      avatar
      skills {
        name
        mastery
        categoryId
      }
      languages {
        name
        proficiency
      }
    }
    department {
      id
      created_at
      name
    }
    position {
      id
      created_at
      name
    }
    cvs {
      id
      created_at
      name
      description
    }
  }
}
