query Skills {
  skills {
    id
    created_at
    name
    category_name
    category_parent_name
    category {
      id
      name
      order
      parent {
        id
        name
        order
      }
      children {
        id
        name
        order
      }
    }
  }
}
