mutation Signup($auth: AuthInput!) {
  signup(auth: $auth) {
    user {
      id
      created_at
      email
      is_verified
      profile {
        id
        first_name
        last_name
        full_name
        avatar
      }
      cvs {
        id
      }
      department {
        id
      }
      department_name
      position {
        id
      }
      position_name
      role
    }
    access_token
    refresh_token
  }
}